### ISSUE TITLE
(tag-)Collections and Collaborators(tag-or-collection-sharing)

### ISSUE THREAD

**Issue by ah548455** [mivp/previs#2]
I have >10 datasets from IRT in my Tag library, 
currently ~5 from the drone platform which might easily ramp up to 50 
and for RISE I am expecting around 100

I would like to be able to pull datasets together by their project( or project partner) in a collection and allow adding a new tag to a certain collection. 

I would like to be able to share a tag or a collection with a collaborator and have that tag show up in their tag-library. 

I am undecided I we should at this point think about sharing settings like "view only,  add-not-modify, full-permission, transfer ownership"

**Comment by ntoand** [comment]
v0.9.0
