### ISSUE TITLE
3b50ea (obj) not working in CAVE

### ISSUE THREAD

**Issue by ah548455** [mivp/previs#38]
Comment AH: Got an email via "mivp-info@monash.edu"  /comment

We have uploaded a dataset (obj) to previs for self-service in the CAVE2.
Tag: 3b50ea

The web preview looked okay, except for some problems with the normals in the obj.
However, loading the dataset in the CAVE2 was not so successful.
The model didn't look at all what we would have expected.
It looked like there were some problems with the clipping planes.
Furthermore, the material file could not be found.
But we believe the dataset has been prepared as detailed in the instructions.

Any feedback would be appreciated!
Thank you!

Kind regards,
Tobias

--
TOBIAS CZAUDERNA, PhD
Research Fellow

**Comment by ntoand** [comment]
LavaVR cannot load the material file because the name of the material file in OBJ is incorrect:

(Pluto-U1100.obj)
# FreeCAD v0.18 build16131 (Git) Arch module
# http://www.freecadweb.org
mtllib Pluto-U1100-2019-10-22_5dae7dc1164c5.mtl

The name of material file is Pluto-U1100.mtl
